export enum CardiErrorTypes {
  ExpiredAccessToken = 'ExpiredAccessToken',
  InvalidAccessToken = 'InvalidAccessToken',
  InvalidCredentials = 'InvalidCredentials',
  MissingAccessToken = 'MissingAccessToken',
  CardNotFound = 'CardNotFound',
  CompanyAlreadyExist = 'CompanyAlreadyExist',
  CompanyNotFound = 'CompanyNotFound',
  PreferencesAlreadyExist = 'PreferencesAlreadyExist',
  PreferencesNotFound = 'PreferencesNotFound',
  PromotionNotFound = 'PromotionNotFound',
  PromotionOutdated = 'PromotionOutdated',
  UserAlreadyExist = 'UserAlreadyExist',
  UserNotFound = 'UserNotFound',
  InvalidUserRole = 'InvalidUserRole',
  SubscriptionAlreadyExist = 'SubscriptionAlreadyExist',
  SubscriptionAlreadyCompleted = 'SubscriptionAlreadyCompleted',
  SubscriptionNotFound = 'SubscriptionNotFound',
  InvalidPromotionType = 'InvalidPromotionType',
  InvalidSusbcriptorRole = 'InvalidSusbcriptorRole',
  WalletNotFound = 'WalletNotFound',
  NotOwned = 'NotOwned',
  Unknown = 'Unknown',
}