export { default as createPromotionController } from './createPromotionController'
export { default as deletePromotionController } from './deletePromotionController'
export { default as getPromotionController } from './getPromotionController'
export { default as getPromotionsController } from './getPromotionsController'
export { default as updatePromotionController } from './updatePromotionController'
