name: Deploy to Railway

on:
  push:
    branches: [main]
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 19
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '19'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
