name: Integration Pipeline

on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches:
      - "**"
    types:
      - "opened"
      - "synchronize"
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:

  integrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node v19
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '19'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test --if-present
