name: Deployment Pipeline

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]
    types: [opened, synchronize]
  workflow_dispatch:

# Cancel Previous Redundant Builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '19'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  
  prettify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '19'
      - name: Prettify code
        run: npx run prettier --write ./src
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '19'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist

  test:
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '19'
      - name: Install dependencies
        run: npm ci
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist
      - name: Test
        run: npm test

  # deploy:
  #   needs: [test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Deploy to Heroku
  #       if: ${{ github.event_name == 'push' }}
  #       uses: akhileshns/heroku-deploy@v3.12.12
  #       with:
  #         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #         heroku_app_name: ${{secrets.HEROKU_APP}}
  #         heroku_email: ${{secrets.HEROKU_API_EMAIL}}
  #         healthcheck: "https://${{secrets.HEROKU_APP}}.herokuapp.com/health"
  #         rollbackonhealthcheckfailed: true